In [1]:
import numpy as np

# Creating Numpy Arrays

### np.array()

In [4]:
# np.array()

list1 = [1,2,3]
array1 = np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim) #check dimension of an array

[1 2 3]
<class 'numpy.ndarray'>
1


In [7]:
list2 = [[1,2],[3,4]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


### np.zeros()

In [11]:
np.zeros(4) # returns float value

array([0., 0., 0., 0.])

In [17]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### np.ones

In [23]:
print(np.ones((2,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


### np.full()

In [24]:
np.full(2,3)

array([3, 3])

In [25]:
np.full((2,3),-3)

array([[-3, -3, -3],
       [-3, -3, -3]])

### np.linspace()

In [ ]:
np.linspace()

### np.arrange()

In [26]:
# np.array (range(start, stop, step))
np.linspace(1,10,2)

array([ 1., 10.])

In [27]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [31]:
print(np.linspace((1,2),(5,10),5)) # multidimension maa spacing anusar print garne

[[ 1.  2.]
 [ 2.  4.]
 [ 3.  6.]
 [ 4.  8.]
 [ 5. 10.]]


### np.diag()

In [32]:
print(np.diag([2,3,4,5]))

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [33]:
print(np.diag([2,3,4,5], k=1))

[[0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]
 [0 0 0 0 0]]


In [34]:
print(np.diag([2,3,4,5], k=-1))

[[0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]]


### np.eye()

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(5, k=-1) # we must use 'k' as a keyword

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### np.identity()

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random.rand()

In [41]:
np.random.rand(2,3)

array([[0.12270536, 0.39778629, 0.19953175],
       [0.53203656, 0.03813755, 0.28191829]])

In [42]:
np.random.rand(2,3)

array([[0.51387607, 0.56196089, 0.40885574],
       [0.55463747, 0.66460093, 0.2106844 ]])

In [43]:
np.random.rand(3,4)

array([[0.2319262 , 0.02543527, 0.05079928, 0.5886789 ],
       [0.2940743 , 0.77070583, 0.92549392, 0.96946755],
       [0.0914919 , 0.45294728, 0.70663401, 0.13137927]])

In [47]:
np.random.randint(2,10, (3,7))

array([[6, 6, 2, 2, 7, 9, 6],
       [8, 4, 3, 3, 4, 7, 6],
       [2, 9, 6, 2, 6, 6, 8]])