In [1]:
list1 = [1,2,3,4,5]
list1[1:3]

[2, 3]

In [4]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5]
array1 = np.array(list1)

In [6]:
array1[1:3]

array([2, 3])

In [7]:
array1[0:5:2]

array([1, 3, 5])

### Multi Dimensional

In [13]:
list2 = [[1,2,3,4,5,6,7,8], [1,3,5,7,9,11,13,15]]

In [14]:
list2[1][3:]

[7, 9, 11, 13, 15]

In [15]:
array2 = np.array(list2)

In [17]:
array2[:,0:4]

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

In [25]:
array2[:,1::2]

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])