In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

2

In [6]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [7]:
a.sum()

21

In [8]:
a.max()

6

In [9]:
a.max(axis=0) #column wise maximum value dinxa

array([4, 5, 6])

In [10]:
a.max(axis=1) #row wise maximym value dinxa

array([3, 6])

In [12]:
a.argmax(axis=1) #kun index ko value maximum xa vanera, index chai dinxa

array([2, 2], dtype=int64)

In [13]:
a.reshape((3,2)) # Note: Product of elements should be conserved

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])

In [15]:
np.concatenate((m,n), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.concatenate((m,n), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
np.concatenate((m,n), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
a=a.reshape(6)

In [20]:
print(a)

[1 2 3 4 5 6]


In [21]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [22]:
np.split(a,[2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]